package rules.filtering_rules;
dialect  "mvel"

import travel_recommendation.model.User;
import travel_recommendation.model.Destination;
import travel_recommendation.model.TransportationType;
import travel_recommendation.model.Location;

rule "Higher score if transportation type is matching"
    salience 1
    agenda-group "grade-destinations"
    lock-on-active
    when
        $u : User()
        $d : Destination(transportationTypes contains $u.transportationType)
    then
        modify($d){setScore($d.getScore()+10)}
end

rule "Higher score if weather is matching"
    salience 1
    agenda-group "grade-destinations"
    lock-on-active
    when
        $u : User()
        $d : Destination(weather == $u.weather)
    then
        modify($d){setScore($d.getScore()+10)}
end

rule "Higher score if destination type is matching"
    salience 1
    agenda-group "grade-destinations"
    lock-on-active
        when
            $u : User()
            $d : Destination(destinationTypes contains $u.destinationType)
        then
            modify($d){setScore($d.getScore()+10)}
end

rule "Higher score if continent is matching"
    salience 1
    agenda-group "grade-destinations"
    lock-on-active
        when
            $u : User()
            $d : Destination(location.continent == $u.continent)
        then
            modify($d){setScore($d.getScore()+10)}
end

rule "Higher score if destination is closer and budget is lower"
    salience 1
    agenda-group "grade-destinations"
    lock-on-active
    when
        $d : Destination($dl : location)
        $u : User($ul : location, Location.distance($dl.getCoordinates(), $ul.getCoordinates()) <= 1500, budget <= 600)
    then
        modify($d){setScore($d.getScore()+15)}
end

rule "Higher score if destination is medium far and budget is medium high"
    salience 1
    agenda-group "grade-destinations"
    lock-on-active
    when
        $d : Destination($dl : location)
        $u : User($ul : location, Location.distance($dl.getCoordinates(), $ul.getCoordinates()) > 1500 && Location.distance($dl.getCoordinates(), $ul.getCoordinates()) <= 2500, budget > 600 && budget <= 1200)
    then
        modify($d){setScore($d.getScore()+15)}
end

rule "Higher score if destination is farer and budget is higher"
    salience 1
    agenda-group "grade-destinations"
    lock-on-active
    when
        $d : Destination($dl : location)
        $u : User($ul : location, Location.distance($dl.getCoordinates(), $ul.getCoordinates()) > 2500, budget > 1200)
    then
        modify($d){setScore($d.getScore()+15)}
end
